Sched = {
    "April": {
        "2021-04-01": [
            [
                "WAS",
                "DET"
            ],
            [
                "PHI",
                "CLE"
            ],
            [
                "CHA",
                "BKN"
            ],
            [
                "GSW",
                "MIA"
            ],
            [
                "ORL",
                "NOP"
            ],
            [
                "ATL",
                "SAS"
            ],
            [
                "DEN",
                "LAC"
            ]
        ],
        "2021-04-02": [
            [
                "GSW",
                "TOR"
            ],
            [
                "HOU",
                "BOS"
            ],
            [
                "DAL",
                "NYK"
            ],
            [
                "CHA",
                "IND"
            ],
            [
                "MIN",
                "MEM"
            ],
            [
                "ATL",
                "NOP"
            ],
            [
                "CHI",
                "UTA"
            ],
            [
                "OKC",
                "PHX"
            ],
            [
                "MIL",
                "POR"
            ],
            [
                "LAL",
                "SAC"
            ]
        ],
        "2021-04-03": [
            [
                "DAL",
                "WAS"
            ],
            [
                "NYK",
                "DET"
            ],
            [
                "CLE",
                "MIA"
            ],
            [
                "MIN",
                "PHI"
            ],
            [
                "IND",
                "SAS"
            ],
            [
                "ORL",
                "UTA"
            ],
            [
                "OKC",
                "POR"
            ],
            [
                "MIL",
                "SAC"
            ]
        ],
        "2021-04-04": [
            [
                "BKN",
                "CHI"
            ],
            [
                "LAL",
                "LAC"
            ],
            [
                "CHA",
                "BOS"
            ],
            [
                "MEM",
                "PHI"
            ],
            [
                "GSW",
                "ATL"
            ],
            [
                "NOP",
                "HOU"
            ],
            [
                "ORL",
                "DEN"
            ]
        ],
        "2021-04-05": [
            [
                "NYK",
                "BKN"
            ],
            [
                "WAS",
                "TOR"
            ],
            [
                "UTA",
                "DAL"
            ],
            [
                "SAC",
                "MIN"
            ],
            [
                "DET",
                "OKC"
            ],
            [
                "CLE",
                "SAS"
            ],
            [
                "PHX",
                "HOU"
            ]
        ],
        "2021-04-06": [
            [
                "CHI",
                "IND"
            ],
            [
                "NOP",
                "ATL"
            ],
            [
                "PHI",
                "BOS"
            ],
            [
                "LAL",
                "TOR"
            ],
            [
                "MEM",
                "MIA"
            ],
            [
                "DET",
                "DEN"
            ],
            [
                "MIL",
                "GSW"
            ],
            [
                "POR",
                "LAC"
            ]
        ],
        "2021-04-07": [
            [
                "MIN",
                "IND"
            ],
            [
                "WAS",
                "ORL"
            ],
            [
                "NYK",
                "BOS"
            ],
            [
                "NOP",
                "BKN"
            ],
            [
                "DAL",
                "HOU"
            ],
            [
                "MEM",
                "ATL"
            ],
            [
                "CHA",
                "OKC"
            ],
            [
                "SAS",
                "DEN"
            ],
            [
                "UTA",
                "PHX"
            ]
        ],
        "2021-04-08": [
            [
                "CHI",
                "TOR"
            ],
            [
                "LAL",
                "MIA"
            ],
            [
                "CLE",
                "OKC"
            ],
            [
                "MIL",
                "DAL"
            ],
            [
                "POR",
                "UTA"
            ],
            [
                "PHX",
                "LAC"
            ],
            [
                "DET",
                "SAC"
            ]
        ],
        "2021-04-09": [
            [
                "IND",
                "ORL"
            ],
            [
                "MIN",
                "BOS"
            ],
            [
                "MEM",
                "NYK"
            ],
            [
                "CHI",
                "ATL"
            ],
            [
                "PHI",
                "NOP"
            ],
            [
                "CHA",
                "MIL"
            ],
            [
                "SAS",
                "DEN"
            ],
            [
                "WAS",
                "GSW"
            ],
            [
                "HOU",
                "LAC"
            ]
        ],
        "2021-04-10": [
            [
                "TOR",
                "CLE"
            ],
            [
                "LAL",
                "BKN"
            ],
            [
                "PHI",
                "OKC"
            ],
            [
                "SAC",
                "UTA"
            ],
            [
                "HOU",
                "GSW"
            ],
            [
                "WAS",
                "PHX"
            ],
            [
                "DET",
                "POR"
            ]
        ],
        "2021-04-11": [
            [
                "ATL",
                "CHA"
            ],
            [
                "BOS",
                "DEN"
            ],
            [
                "NOP",
                "CLE"
            ],
            [
                "MIL",
                "ORL"
            ],
            [
                "TOR",
                "NYK"
            ],
            [
                "SAS",
                "DAL"
            ],
            [
                "IND",
                "MEM"
            ],
            [
                "CHI",
                "MIN"
            ],
            [
                "DET",
                "LAC"
            ],
            [
                "MIA",
                "POR"
            ]
        ],
        "2021-04-12": [
            [
                "LAL",
                "NYK"
            ],
            [
                "PHI",
                "DAL"
            ],
            [
                "SAS",
                "ORL"
            ],
            [
                "CHI",
                "MEM"
            ],
            [
                "SAC",
                "NOP"
            ],
            [
                "WAS",
                "UTA"
            ],
            [
                "DEN",
                "GSW"
            ],
            [
                "HOU",
                "PHX"
            ]
        ],
        "2021-04-13": [
            [
                "BKN",
                "MIN"
            ],
            [
                "LAC",
                "IND"
            ],
            [
                "ATL",
                "TOR"
            ],
            [
                "LAL",
                "CHA"
            ],
            [
                "OKC",
                "UTA"
            ],
            [
                "MIA",
                "PHX"
            ],
            [
                "BOS",
                "POR"
            ]
        ],
        "2021-04-14": [
            [
                "MIL",
                "MIN"
            ],
            [
                "CLE",
                "CHA"
            ],
            [
                "BKN",
                "PHI"
            ],
            [
                "SAS",
                "TOR"
            ],
            [
                "LAC",
                "DET"
            ],
            [
                "ORL",
                "CHI"
            ],
            [
                "NYK",
                "NOP"
            ],
            [
                "IND",
                "HOU"
            ],
            [
                "GSW",
                "OKC"
            ],
            [
                "DAL",
                "MEM"
            ],
            [
                "MIA",
                "DEN"
            ],
            [
                "WAS",
                "SAC"
            ]
        ],
        "2021-04-15": [
            [
                "MIL",
                "ATL"
            ],
            [
                "GSW",
                "CLE"
            ],
            [
                "BOS",
                "LAL"
            ],
            [
                "SAC",
                "PHX"
            ]
        ],
        "2021-04-16": [
            [
                "IND",
                "UTA"
            ],
            [
                "OKC",
                "DET"
            ],
            [
                "LAC",
                "PHI"
            ],
            [
                "NOP",
                "WAS"
            ],
            [
                "CHA",
                "BKN"
            ],
            [
                "ORL",
                "TOR"
            ],
            [
                "MEM",
                "CHI"
            ],
            [
                "DEN",
                "HOU"
            ],
            [
                "MIA",
                "MIN"
            ],
            [
                "POR",
                "SAS"
            ],
            [
                "NYK",
                "DAL"
            ]
        ],
        "2021-04-17": [
            [
                "UTA",
                "LAL"
            ],
            [
                "DET",
                "WAS"
            ],
            [
                "CLE",
                "CHI"
            ],
            [
                "GSW",
                "BOS"
            ],
            [
                "MEM",
                "MIL"
            ],
            [
                "SAS",
                "PHX"
            ]
        ],
        "2021-04-18": [
            [
                "IND",
                "ATL"
            ],
            [
                "NOP",
                "NYK"
            ],
            [
                "BKN",
                "MIA"
            ],
            [
                "POR",
                "CHA"
            ],
            [
                "HOU",
                "ORL"
            ],
            [
                "OKC",
                "TOR"
            ],
            [
                "SAC",
                "DAL"
            ],
            [
                "MIN",
                "LAC"
            ]
        ],
        "2021-04-19": [
            [
                "CLE",
                "DET"
            ],
            [
                "CHI",
                "BOS"
            ],
            [
                "GSW",
                "PHI"
            ],
            [
                "SAS",
                "IND"
            ],
            [
                "HOU",
                "MIA"
            ],
            [
                "OKC",
                "WAS"
            ],
            [
                "PHX",
                "MIL"
            ],
            [
                "MEM",
                "DEN"
            ],
            [
                "UTA",
                "LAL"
            ]
        ],
        "2021-04-20": [
            [
                "ORL",
                "ATL"
            ],
            [
                "CHA",
                "NYK"
            ],
            [
                "BKN",
                "NOP"
            ],
            [
                "LAC",
                "POR"
            ],
            [
                "MIN",
                "SAC"
            ]
        ],
        "2021-04-21": [
            [
                "CHI",
                "CLE"
            ],
            [
                "OKC",
                "IND"
            ],
            [
                "PHX",
                "PHI"
            ],
            [
                "BKN",
                "TOR"
            ],
            [
                "GSW",
                "WAS"
            ],
            [
                "ATL",
                "NYK"
            ],
            [
                "UTA",
                "HOU"
            ],
            [
                "DET",
                "DAL"
            ],
            [
                "MIA",
                "SAS"
            ],
            [
                "MEM",
                "LAC"
            ],
            [
                "DEN",
                "POR"
            ],
            [
                "MIN",
                "SAC"
            ]
        ],
        "2021-04-22": [
            [
                "PHX",
                "BOS"
            ],
            [
                "NOP",
                "ORL"
            ],
            [
                "PHI",
                "MIL"
            ],
            [
                "DET",
                "SAS"
            ],
            [
                "CHA",
                "CHI"
            ],
            [
                "LAL",
                "DAL"
            ]
        ],
        "2021-04-23": [
            [
                "MIA",
                "ATL"
            ],
            [
                "BOS",
                "BKN"
            ],
            [
                "CLE",
                "CHA"
            ],
            [
                "LAC",
                "HOU"
            ],
            [
                "WAS",
                "OKC"
            ],
            [
                "MEM",
                "POR"
            ],
            [
                "DEN",
                "GSW"
            ]
        ],
        "2021-04-24": [
            [
                "TOR",
                "NYK"
            ],
            [
                "PHI",
                "MIL"
            ],
            [
                "DET",
                "IND"
            ],
            [
                "SAS",
                "NOP"
            ],
            [
                "CHI",
                "MIA"
            ],
            [
                "LAL",
                "DAL"
            ],
            [
                "MIN",
                "UTA"
            ],
            [
                "HOU",
                "DEN"
            ]
        ],
        "2021-04-25": [
            [
                "BOS",
                "CHA"
            ],
            [
                "PHX",
                "BKN"
            ],
            [
                "MEM",
                "POR"
            ],
            [
                "CLE",
                "WAS"
            ],
            [
                "MIL",
                "ATL"
            ],
            [
                "IND",
                "ORL"
            ],
            [
                "SAC",
                "GSW"
            ]
        ],
        "2021-04-26": [
            [
                "ATL",
                "DET"
            ],
            [
                "LAL",
                "ORL"
            ],
            [
                "OKC",
                "PHI"
            ],
            [
                "SAS",
                "WAS"
            ],
            [
                "PHX",
                "NYK"
            ],
            [
                "CLE",
                "TOR"
            ],
            [
                "CHI",
                "MIA"
            ],
            [
                "UTA",
                "MIN"
            ],
            [
                "LAC",
                "NOP"
            ],
            [
                "MEM",
                "DEN"
            ],
            [
                "DAL",
                "SAC"
            ]
        ],
        "2021-04-27": [
            [
                "OKC",
                "BOS"
            ],
            [
                "MIL",
                "CHA"
            ],
            [
                "POR",
                "IND"
            ],
            [
                "BKN",
                "TOR"
            ],
            [
                "MIN",
                "HOU"
            ],
            [
                "DAL",
                "GSW"
            ]
        ],
        "2021-04-28": [
            [
                "ORL",
                "CLE"
            ],
            [
                "ATL",
                "PHI"
            ],
            [
                "LAL",
                "WAS"
            ],
            [
                "CHA",
                "BOS"
            ],
            [
                "CHI",
                "NYK"
            ],
            [
                "SAS",
                "MIA"
            ],
            [
                "POR",
                "MEM"
            ],
            [
                "NOP",
                "DEN"
            ],
            [
                "LAC",
                "PHX"
            ],
            [
                "UTA",
                "SAC"
            ]
        ],
        "2021-04-29": [
            [
                "DAL",
                "DET"
            ],
            [
                "BKN",
                "IND"
            ],
            [
                "MIL",
                "HOU"
            ],
            [
                "GSW",
                "MIN"
            ],
            [
                "NOP",
                "OKC"
            ],
            [
                "TOR",
                "DEN"
            ]
        ],
        "2021-04-30": [
            [
                "ATL",
                "PHI"
            ],
            [
                "SAS",
                "BOS"
            ],
            [
                "WAS",
                "CLE"
            ],
            [
                "POR",
                "BKN"
            ],
            [
                "ORL",
                "MEM"
            ],
            [
                "MIL",
                "CHI"
            ],
            [
                "UTA",
                "PHX"
            ],
            [
                "SAC",
                "LAL"
            ]
        ]
    },
    "December": {
        "2020-12-11": [
            [
                "ORL",
                "ATL"
            ],
            [
                "NYK",
                "DET"
            ],
            [
                "HOU",
                "CHI"
            ],
            [
                "LAC",
                "LAL"
            ],
            [
                "SAC",
                "POR"
            ]
        ],
        "2020-12-12": [
            [
                "TOR",
                "CHA"
            ],
            [
                "IND",
                "CLE"
            ],
            [
                "OKC",
                "SAS"
            ],
            [
                "DAL",
                "MIL"
            ],
            [
                "MEM",
                "MIN"
            ],
            [
                "DEN",
                "GSW"
            ],
            [
                "PHX",
                "UTA"
            ]
        ],
        "2020-12-13": [
            [
                "ORL",
                "ATL"
            ],
            [
                "WAS",
                "BKN"
            ],
            [
                "NYK",
                "DET"
            ],
            [
                "HOU",
                "CHI"
            ],
            [
                "LAC",
                "LAL"
            ],
            [
                "SAC",
                "POR"
            ]
        ],
        "2020-12-14": [
            [
                "IND",
                "CLE"
            ],
            [
                "TOR",
                "CHA"
            ],
            [
                "NOP",
                "MIA"
            ],
            [
                "DAL",
                "MIL"
            ],
            [
                "MEM",
                "MIN"
            ],
            [
                "PHX",
                "UTA"
            ]
        ],
        "2020-12-15": [
            [
                "BOS",
                "PHI"
            ],
            [
                "SAS",
                "HOU"
            ],
            [
                "GSW",
                "SAC"
            ]
        ],
        "2020-12-16": [
            [
                "CLE",
                "NYK"
            ],
            [
                "CHI",
                "OKC"
            ],
            [
                "POR",
                "DEN"
            ],
            [
                "LAL",
                "PHX"
            ]
        ],
        "2020-12-17": [
            [
                "CHA",
                "ORL"
            ],
            [
                "DET",
                "WAS"
            ],
            [
                "SAS",
                "HOU"
            ],
            [
                "ATL",
                "MEM"
            ],
            [
                "MIN",
                "DAL"
            ],
            [
                "GSW",
                "SAC"
            ],
            [
                "UTA",
                "LAC"
            ]
        ],
        "2020-12-18": [
            [
                "PHI",
                "IND"
            ],
            [
                "MIA",
                "TOR"
            ],
            [
                "CLE",
                "NYK"
            ],
            [
                "BKN",
                "BOS"
            ],
            [
                "MIL",
                "NOP"
            ],
            [
                "CHI",
                "OKC"
            ],
            [
                "POR",
                "DEN"
            ],
            [
                "LAL",
                "PHX"
            ]
        ],
        "2020-12-19": [
            [
                "CHA",
                "ORL"
            ],
            [
                "DET",
                "WAS"
            ],
            [
                "ATL",
                "MEM"
            ]
        ],
        "2020-12-22": [
            [
                "GSW",
                "BKN"
            ],
            [
                "LAC",
                "LAL"
            ]
        ],
        "2020-12-23": [
            [
                "CHA",
                "CLE"
            ],
            [
                "NYK",
                "IND"
            ],
            [
                "MIA",
                "ORL"
            ],
            [
                "WAS",
                "PHI"
            ],
            [
                "MIL",
                "BOS"
            ],
            [
                "NOP",
                "TOR"
            ],
            [
                "ATL",
                "CHI"
            ],
            [
                "SAS",
                "MEM"
            ],
            [
                "DET",
                "MIN"
            ],
            [
                "SAC",
                "DEN"
            ],
            [
                "UTA",
                "POR"
            ],
            [
                "DAL",
                "PHX"
            ]
        ],
        "2020-12-25": [
            [
                "NOP",
                "MIA"
            ],
            [
                "GSW",
                "MIL"
            ],
            [
                "BKN",
                "BOS"
            ],
            [
                "DAL",
                "LAL"
            ],
            [
                "LAC",
                "DEN"
            ]
        ],
        "2020-12-26": [
            [
                "ATL",
                "MEM"
            ],
            [
                "OKC",
                "CHA"
            ],
            [
                "CLE",
                "DET"
            ],
            [
                "ORL",
                "WAS"
            ],
            [
                "PHI",
                "NYK"
            ],
            [
                "IND",
                "CHI"
            ],
            [
                "TOR",
                "SAS"
            ],
            [
                "MIN",
                "UTA"
            ],
            [
                "HOU",
                "POR"
            ],
            [
                "PHX",
                "SAC"
            ]
        ],
        "2020-12-27": [
            [
                "DAL",
                "LAC"
            ],
            [
                "BKN",
                "CHA"
            ],
            [
                "ORL",
                "WAS"
            ],
            [
                "SAS",
                "NOP"
            ],
            [
                "PHI",
                "CLE"
            ],
            [
                "MIL",
                "NYK"
            ],
            [
                "BOS",
                "IND"
            ],
            [
                "GSW",
                "CHI"
            ],
            [
                "PHX",
                "SAC"
            ],
            [
                "MIN",
                "LAL"
            ]
        ],
        "2020-12-28": [
            [
                "DET",
                "ATL"
            ],
            [
                "MEM",
                "BKN"
            ],
            [
                "UTA",
                "OKC"
            ],
            [
                "HOU",
                "DEN"
            ],
            [
                "POR",
                "LAL"
            ]
        ],
        "2020-12-29": [
            [
                "NYK",
                "CLE"
            ],
            [
                "GSW",
                "DET"
            ],
            [
                "BOS",
                "IND"
            ],
            [
                "TOR",
                "PHI"
            ],
            [
                "CHI",
                "WAS"
            ],
            [
                "MIL",
                "MIA"
            ],
            [
                "ORL",
                "OKC"
            ],
            [
                "NOP",
                "PHX"
            ],
            [
                "MIN",
                "LAC"
            ],
            [
                "DEN",
                "SAC"
            ]
        ],
        "2020-12-30": [
            [
                "MEM",
                "BOS"
            ],
            [
                "ATL",
                "BKN"
            ],
            [
                "MIL",
                "MIA"
            ],
            [
                "CHA",
                "DAL"
            ],
            [
                "LAL",
                "SAS"
            ],
            [
                "POR",
                "LAC"
            ]
        ],
        "2020-12-31": [
            [
                "CLE",
                "IND"
            ],
            [
                "CHI",
                "WAS"
            ],
            [
                "PHI",
                "ORL"
            ],
            [
                "SAC",
                "HOU"
            ],
            [
                "NYK",
                "TOR"
            ],
            [
                "NOP",
                "OKC"
            ],
            [
                "PHX",
                "UTA"
            ]
        ]
    },
    "February": {
        "2021-02-01": [
            [
                "LAL",
                "ATL"
            ],
            [
                "CHA",
                "MIA"
            ],
            [
                "MIN",
                "CLE"
            ],
            [
                "NYK",
                "CHI"
            ],
            [
                "POR",
                "MIL"
            ],
            [
                "SAC",
                "NOP"
            ],
            [
                "HOU",
                "OKC"
            ],
            [
                "PHX",
                "DAL"
            ],
            [
                "MEM",
                "SAS"
            ]
        ],
        "2021-02-02": [
            [
                "TOR",
                "ORL"
            ],
            [
                "LAC",
                "BKN"
            ],
            [
                "MEM",
                "IND"
            ],
            [
                "POR",
                "WAS"
            ],
            [
                "DET",
                "UTA"
            ],
            [
                "BOS",
                "GSW"
            ]
        ],
        "2021-02-03": [
            [
                "PHI",
                "CHA"
            ],
            [
                "IND",
                "MIL"
            ],
            [
                "DAL",
                "ATL"
            ],
            [
                "LAC",
                "CLE"
            ],
            [
                "WAS",
                "MIA"
            ],
            [
                "NYK",
                "CHI"
            ],
            [
                "HOU",
                "OKC"
            ],
            [
                "MIN",
                "SAS"
            ],
            [
                "PHX",
                "NOP"
            ],
            [
                "BOS",
                "SAC"
            ]
        ],
        "2021-02-04": [
            [
                "UTA",
                "ATL"
            ],
            [
                "GSW",
                "DAL"
            ],
            [
                "POR",
                "PHI"
            ],
            [
                "HOU",
                "MEM"
            ],
            [
                "DEN",
                "LAL"
            ]
        ],
        "2021-02-05": [
            [
                "NOP",
                "IND"
            ],
            [
                "CHI",
                "ORL"
            ],
            [
                "TOR",
                "BKN"
            ],
            [
                "MIL",
                "CLE"
            ],
            [
                "UTA",
                "CHA"
            ],
            [
                "WAS",
                "MIA"
            ],
            [
                "MIN",
                "OKC"
            ],
            [
                "DET",
                "PHX"
            ],
            [
                "BOS",
                "LAC"
            ]
        ],
        "2021-02-06": [
            [
                "POR",
                "NYK"
            ],
            [
                "DEN",
                "SAC"
            ],
            [
                "CHI",
                "ORL"
            ],
            [
                "BKN",
                "PHI"
            ],
            [
                "TOR",
                "ATL"
            ],
            [
                "MIL",
                "CLE"
            ],
            [
                "SAS",
                "HOU"
            ],
            [
                "MIN",
                "OKC"
            ],
            [
                "GSW",
                "DAL"
            ],
            [
                "MEM",
                "NOP"
            ],
            [
                "DET",
                "LAL"
            ]
        ],
        "2021-02-07": [
            [
                "WAS",
                "CHA"
            ],
            [
                "UTA",
                "IND"
            ],
            [
                "MIA",
                "NYK"
            ],
            [
                "BOS",
                "PHX"
            ],
            [
                "SAC",
                "LAC"
            ]
        ],
        "2021-02-08": [
            [
                "HOU",
                "CHA"
            ],
            [
                "WAS",
                "CHI"
            ],
            [
                "TOR",
                "MEM"
            ],
            [
                "MIN",
                "DAL"
            ],
            [
                "GSW",
                "SAS"
            ],
            [
                "CLE",
                "PHX"
            ],
            [
                "MIL",
                "DEN"
            ],
            [
                "OKC",
                "LAL"
            ]
        ],
        "2021-02-09": [
            [
                "BKN",
                "DET"
            ],
            [
                "NYK",
                "MIA"
            ],
            [
                "HOU",
                "NOP"
            ],
            [
                "GSW",
                "SAS"
            ],
            [
                "BOS",
                "UTA"
            ],
            [
                "ORL",
                "POR"
            ],
            [
                "PHI",
                "SAC"
            ]
        ],
        "2021-02-10": [
            [
                "TOR",
                "WAS"
            ],
            [
                "ATL",
                "DAL"
            ],
            [
                "IND",
                "BKN"
            ],
            [
                "CHA",
                "MEM"
            ],
            [
                "LAC",
                "MIN"
            ],
            [
                "NOP",
                "CHI"
            ],
            [
                "CLE",
                "DEN"
            ],
            [
                "MIL",
                "PHX"
            ],
            [
                "OKC",
                "LAL"
            ]
        ],
        "2021-02-11": [
            [
                "MIA",
                "HOU"
            ],
            [
                "TOR",
                "BOS"
            ],
            [
                "IND",
                "DET"
            ],
            [
                "ORL",
                "GSW"
            ],
            [
                "PHI",
                "POR"
            ]
        ],
        "2021-02-12": [
            [
                "MIN",
                "CHA"
            ],
            [
                "NYK",
                "WAS"
            ],
            [
                "SAS",
                "ATL"
            ],
            [
                "NOP",
                "DAL"
            ],
            [
                "LAC",
                "CHI"
            ],
            [
                "DET",
                "BOS"
            ],
            [
                "OKC",
                "DEN"
            ],
            [
                "MIL",
                "UTA"
            ],
            [
                "MEM",
                "LAL"
            ],
            [
                "CLE",
                "POR"
            ],
            [
                "ORL",
                "SAC"
            ]
        ],
        "2021-02-13": [
            [
                "PHI",
                "PHX"
            ],
            [
                "IND",
                "ATL"
            ],
            [
                "HOU",
                "NYK"
            ],
            [
                "BKN",
                "GSW"
            ],
            [
                "MIA",
                "UTA"
            ]
        ],
        "2021-02-14": [
            [
                "BOS",
                "WAS"
            ],
            [
                "MIN",
                "TOR"
            ],
            [
                "SAS",
                "CHA"
            ],
            [
                "NOP",
                "DET"
            ],
            [
                "POR",
                "DAL"
            ],
            [
                "MIL",
                "OKC"
            ],
            [
                "ORL",
                "PHX"
            ],
            [
                "LAL",
                "DEN"
            ],
            [
                "MEM",
                "SAC"
            ],
            [
                "CLE",
                "LAC"
            ]
        ],
        "2021-02-15": [
            [
                "CHI",
                "IND"
            ],
            [
                "HOU",
                "WAS"
            ],
            [
                "ATL",
                "NYK"
            ],
            [
                "PHI",
                "UTA"
            ],
            [
                "CLE",
                "GSW"
            ],
            [
                "MIA",
                "LAC"
            ],
            [
                "BKN",
                "SAC"
            ]
        ],
        "2021-02-16": [
            [
                "DEN",
                "BOS"
            ],
            [
                "NOP",
                "MEM"
            ],
            [
                "TOR",
                "MIL"
            ],
            [
                "LAL",
                "MIN"
            ],
            [
                "POR",
                "OKC"
            ],
            [
                "BKN",
                "PHX"
            ]
        ],
        "2021-02-17": [
            [
                "NYK",
                "ORL"
            ],
            [
                "ATL",
                "BOS"
            ],
            [
                "HOU",
                "PHI"
            ],
            [
                "DEN",
                "WAS"
            ],
            [
                "IND",
                "MIN"
            ],
            [
                "DET",
                "CHI"
            ],
            [
                "POR",
                "NOP"
            ],
            [
                "OKC",
                "MEM"
            ],
            [
                "MIA",
                "GSW"
            ],
            [
                "UTA",
                "LAC"
            ]
        ],
        "2021-02-18": [
            [
                "TOR",
                "MIL"
            ],
            [
                "BKN",
                "LAL"
            ],
            [
                "MIA",
                "SAC"
            ]
        ],
        "2021-02-19": [
            [
                "GSW",
                "ORL"
            ],
            [
                "DEN",
                "CLE"
            ],
            [
                "CHI",
                "PHI"
            ],
            [
                "ATL",
                "BOS"
            ],
            [
                "DET",
                "MEM"
            ],
            [
                "OKC",
                "MIL"
            ],
            [
                "PHX",
                "NOP"
            ],
            [
                "TOR",
                "MIN"
            ],
            [
                "UTA",
                "LAC"
            ]
        ],
        "2021-02-20": [
            [
                "GSW",
                "CHA"
            ],
            [
                "MIA",
                "LAL"
            ],
            [
                "SAC",
                "CHI"
            ],
            [
                "PHX",
                "MEM"
            ],
            [
                "WAS",
                "POR"
            ]
        ],
        "2021-02-21": [
            [
                "BOS",
                "NOP"
            ],
            [
                "OKC",
                "CLE"
            ],
            [
                "DET",
                "ORL"
            ],
            [
                "PHI",
                "TOR"
            ],
            [
                "MIN",
                "NYK"
            ],
            [
                "DEN",
                "ATL"
            ],
            [
                "BKN",
                "LAC"
            ],
            [
                "SAC",
                "MIL"
            ]
        ],
        "2021-02-22": [
            [
                "CHI",
                "HOU"
            ],
            [
                "MEM",
                "DAL"
            ],
            [
                "MIA",
                "OKC"
            ],
            [
                "POR",
                "PHX"
            ],
            [
                "CHA",
                "UTA"
            ],
            [
                "WAS",
                "LAL"
            ]
        ],
        "2021-02-23": [
            [
                "ATL",
                "CLE"
            ],
            [
                "DET",
                "ORL"
            ],
            [
                "SAC",
                "BKN"
            ],
            [
                "GSW",
                "NYK"
            ],
            [
                "PHI",
                "TOR"
            ],
            [
                "BOS",
                "DAL"
            ],
            [
                "MIN",
                "MIL"
            ],
            [
                "POR",
                "DEN"
            ],
            [
                "WAS",
                "LAC"
            ]
        ],
        "2021-02-24": [
            [
                "GSW",
                "IND"
            ],
            [
                "BOS",
                "ATL"
            ],
            [
                "HOU",
                "CLE"
            ],
            [
                "TOR",
                "MIA"
            ],
            [
                "MIN",
                "CHI"
            ],
            [
                "DET",
                "NOP"
            ],
            [
                "SAS",
                "OKC"
            ],
            [
                "CHA",
                "PHX"
            ],
            [
                "LAL",
                "UTA"
            ]
        ],
        "2021-02-25": [
            [
                "DAL",
                "PHI"
            ],
            [
                "ORL",
                "BKN"
            ],
            [
                "SAC",
                "NYK"
            ],
            [
                "LAC",
                "MEM"
            ],
            [
                "WAS",
                "DEN"
            ],
            [
                "NOP",
                "MIL"
            ]
        ],
        "2021-02-26": [
            [
                "IND",
                "BOS"
            ],
            [
                "HOU",
                "TOR"
            ],
            [
                "SAC",
                "DET"
            ],
            [
                "UTA",
                "MIA"
            ],
            [
                "PHX",
                "CHI"
            ],
            [
                "LAC",
                "MEM"
            ],
            [
                "ATL",
                "OKC"
            ],
            [
                "CHA",
                "GSW"
            ],
            [
                "POR",
                "LAL"
            ]
        ],
        "2021-02-27": [
            [
                "CLE",
                "PHI"
            ],
            [
                "MIN",
                "WAS"
            ],
            [
                "NOP",
                "SAS"
            ],
            [
                "IND",
                "NYK"
            ],
            [
                "UTA",
                "ORL"
            ],
            [
                "DEN",
                "OKC"
            ],
            [
                "DAL",
                "BKN"
            ]
        ],
        "2021-02-28": [
            [
                "LAC",
                "MIL"
            ],
            [
                "WAS",
                "BOS"
            ],
            [
                "NYK",
                "DET"
            ],
            [
                "ATL",
                "MIA"
            ],
            [
                "MEM",
                "HOU"
            ],
            [
                "GSW",
                "LAL"
            ],
            [
                "PHX",
                "MIN"
            ],
            [
                "CHA",
                "SAC"
            ]
        ]
    },
    "January": {
        "2021-01-01": [
            [
                "MEM",
                "CHA"
            ],
            [
                "BOS",
                "DET"
            ],
            [
                "MIA",
                "DAL"
            ],
            [
                "ATL",
                "BKN"
            ],
            [
                "CHI",
                "MIL"
            ],
            [
                "WAS",
                "MIN"
            ],
            [
                "LAL",
                "SAS"
            ],
            [
                "PHX",
                "DEN"
            ],
            [
                "LAC",
                "UTA"
            ],
            [
                "POR",
                "GSW"
            ]
        ],
        "2021-01-02": [
            [
                "SAC",
                "HOU"
            ],
            [
                "NYK",
                "IND"
            ],
            [
                "OKC",
                "ORL"
            ],
            [
                "CHA",
                "PHI"
            ],
            [
                "CLE",
                "ATL"
            ],
            [
                "TOR",
                "NOP"
            ]
        ],
        "2021-01-03": [
            [
                "BOS",
                "DET"
            ],
            [
                "WAS",
                "BKN"
            ],
            [
                "LAL",
                "MEM"
            ],
            [
                "DEN",
                "MIN"
            ],
            [
                "UTA",
                "SAS"
            ],
            [
                "DAL",
                "CHI"
            ],
            [
                "LAC",
                "PHX"
            ],
            [
                "POR",
                "GSW"
            ]
        ],
        "2021-01-04": [
            [
                "CLE",
                "ORL"
            ],
            [
                "CHA",
                "PHI"
            ],
            [
                "NYK",
                "ATL"
            ],
            [
                "OKC",
                "MIA"
            ],
            [
                "BOS",
                "TOR"
            ],
            [
                "DAL",
                "HOU"
            ],
            [
                "DET",
                "MIL"
            ],
            [
                "IND",
                "NOP"
            ],
            [
                "SAC",
                "GSW"
            ]
        ],
        "2021-01-05": [
            [
                "UTA",
                "BKN"
            ],
            [
                "LAL",
                "MEM"
            ],
            [
                "MIN",
                "DEN"
            ],
            [
                "SAS",
                "LAC"
            ],
            [
                "CHI",
                "POR"
            ]
        ],
        "2021-01-06": [
            [
                "HOU",
                "IND"
            ],
            [
                "CLE",
                "ORL"
            ],
            [
                "WAS",
                "PHI"
            ],
            [
                "CHA",
                "ATL"
            ],
            [
                "BOS",
                "MIA"
            ],
            [
                "UTA",
                "NYK"
            ],
            [
                "DET",
                "MIL"
            ],
            [
                "OKC",
                "NOP"
            ],
            [
                "TOR",
                "PHX"
            ],
            [
                "LAC",
                "GSW"
            ],
            [
                "CHI",
                "SAC"
            ]
        ],
        "2021-01-07": [
            [
                "PHI",
                "BKN"
            ],
            [
                "CLE",
                "MEM"
            ],
            [
                "DAL",
                "DEN"
            ],
            [
                "SAS",
                "LAL"
            ],
            [
                "MIN",
                "POR"
            ]
        ],
        "2021-01-08": [
            [
                "PHX",
                "DET"
            ],
            [
                "WAS",
                "BOS"
            ],
            [
                "OKC",
                "NYK"
            ],
            [
                "CHA",
                "NOP"
            ],
            [
                "ORL",
                "HOU"
            ],
            [
                "BKN",
                "MEM"
            ],
            [
                "UTA",
                "MIL"
            ],
            [
                "LAC",
                "GSW"
            ],
            [
                "CHI",
                "LAL"
            ],
            [
                "TOR",
                "SAC"
            ]
        ],
        "2021-01-09": [
            [
                "DEN",
                "PHI"
            ],
            [
                "ATL",
                "CHA"
            ],
            [
                "PHX",
                "IND"
            ],
            [
                "MIA",
                "WAS"
            ],
            [
                "CLE",
                "MIL"
            ],
            [
                "SAS",
                "MIN"
            ],
            [
                "ORL",
                "DAL"
            ],
            [
                "POR",
                "SAC"
            ]
        ],
        "2021-01-10": [
            [
                "UTA",
                "DET"
            ],
            [
                "CHI",
                "LAC"
            ],
            [
                "OKC",
                "BKN"
            ],
            [
                "DEN",
                "NYK"
            ],
            [
                "LAL",
                "HOU"
            ],
            [
                "SAS",
                "MIN"
            ],
            [
                "TOR",
                "GSW"
            ]
        ],
        "2021-01-11": [
            [
                "NYK",
                "CHA"
            ],
            [
                "MEM",
                "CLE"
            ],
            [
                "MIL",
                "ORL"
            ],
            [
                "PHX",
                "WAS"
            ],
            [
                "PHI",
                "ATL"
            ],
            [
                "TOR",
                "POR"
            ],
            [
                "IND",
                "SAC"
            ]
        ],
        "2021-01-12": [
            [
                "MIA",
                "PHI"
            ],
            [
                "DEN",
                "BKN"
            ],
            [
                "UTA",
                "CLE"
            ],
            [
                "LAL",
                "HOU"
            ],
            [
                "SAS",
                "OKC"
            ],
            [
                "IND",
                "GSW"
            ]
        ],
        "2021-01-13": [
            [
                "DAL",
                "CHA"
            ],
            [
                "MIL",
                "DET"
            ],
            [
                "BKN",
                "NYK"
            ],
            [
                "MEM",
                "MIN"
            ],
            [
                "LAL",
                "OKC"
            ],
            [
                "NOP",
                "LAC"
            ],
            [
                "POR",
                "SAC"
            ]
        ],
        "2021-01-14": [
            [
                "MIA",
                "PHI"
            ],
            [
                "CHA",
                "TOR"
            ],
            [
                "HOU",
                "SAS"
            ],
            [
                "GSW",
                "DEN"
            ],
            [
                "IND",
                "POR"
            ]
        ],
        "2021-01-15": [
            [
                "ORL",
                "BOS"
            ],
            [
                "NYK",
                "CLE"
            ],
            [
                "DAL",
                "MIL"
            ],
            [
                "CHI",
                "OKC"
            ],
            [
                "ATL",
                "UTA"
            ],
            [
                "NOP",
                "LAL"
            ],
            [
                "LAC",
                "SAC"
            ]
        ],
        "2021-01-16": [
            [
                "HOU",
                "SAS"
            ],
            [
                "ORL",
                "BKN"
            ],
            [
                "CHA",
                "TOR"
            ],
            [
                "DET",
                "MIA"
            ],
            [
                "PHI",
                "MEM"
            ],
            [
                "ATL",
                "POR"
            ]
        ],
        "2021-01-17": [
            [
                "NYK",
                "BOS"
            ],
            [
                "CHI",
                "DAL"
            ],
            [
                "UTA",
                "DEN"
            ],
            [
                "NOP",
                "SAC"
            ],
            [
                "IND",
                "LAC"
            ]
        ],
        "2021-01-18": [
            [
                "ORL",
                "NYK"
            ],
            [
                "MIN",
                "ATL"
            ],
            [
                "SAS",
                "POR"
            ],
            [
                "PHX",
                "MEM"
            ],
            [
                "MIL",
                "BKN"
            ],
            [
                "DAL",
                "TOR"
            ],
            [
                "DET",
                "MIA"
            ],
            [
                "HOU",
                "CHI"
            ],
            [
                "GSW",
                "LAL"
            ]
        ],
        "2021-01-19": [
            [
                "OKC",
                "DEN"
            ],
            [
                "NOP",
                "UTA"
            ]
        ],
        "2021-01-20": [
            [
                "BKN",
                "CLE"
            ],
            [
                "DAL",
                "IND"
            ],
            [
                "BOS",
                "PHI"
            ],
            [
                "DET",
                "ATL"
            ],
            [
                "MIA",
                "TOR"
            ],
            [
                "ORL",
                "MIN"
            ],
            [
                "PHX",
                "HOU"
            ],
            [
                "SAS",
                "GSW"
            ],
            [
                "SAC",
                "LAC"
            ]
        ],
        "2021-01-21": [
            [
                "LAL",
                "MIL"
            ],
            [
                "NOP",
                "UTA"
            ],
            [
                "NYK",
                "GSW"
            ]
        ],
        "2021-01-22": [
            [
                "CHI",
                "CHA"
            ],
            [
                "HOU",
                "DET"
            ],
            [
                "ORL",
                "IND"
            ],
            [
                "BKN",
                "CLE"
            ],
            [
                "BOS",
                "PHI"
            ],
            [
                "MIA",
                "TOR"
            ],
            [
                "ATL",
                "MIN"
            ],
            [
                "DAL",
                "SAS"
            ],
            [
                "DEN",
                "PHX"
            ],
            [
                "OKC",
                "LAC"
            ],
            [
                "NYK",
                "SAC"
            ]
        ],
        "2021-01-23": [
            [
                "PHI",
                "DET"
            ],
            [
                "MIA",
                "BKN"
            ],
            [
                "NOP",
                "MIN"
            ],
            [
                "GSW",
                "UTA"
            ],
            [
                "LAL",
                "CHI"
            ],
            [
                "HOU",
                "DAL"
            ],
            [
                "DEN",
                "PHX"
            ]
        ],
        "2021-01-24": [
            [
                "TOR",
                "IND"
            ],
            [
                "OKC",
                "LAC"
            ],
            [
                "CLE",
                "BOS"
            ],
            [
                "CHA",
                "ORL"
            ],
            [
                "WAS",
                "SAS"
            ],
            [
                "ATL",
                "MIL"
            ],
            [
                "NYK",
                "POR"
            ]
        ],
        "2021-01-25": [
            [
                "PHI",
                "DET"
            ],
            [
                "TOR",
                "IND"
            ],
            [
                "CHA",
                "ORL"
            ],
            [
                "MIA",
                "BKN"
            ],
            [
                "LAL",
                "CLE"
            ],
            [
                "DEN",
                "DAL"
            ],
            [
                "BOS",
                "CHI"
            ],
            [
                "MIN",
                "GSW"
            ],
            [
                "OKC",
                "POR"
            ]
        ],
        "2021-01-26": [
            [
                "LAC",
                "ATL"
            ],
            [
                "WAS",
                "HOU"
            ],
            [
                "NYK",
                "UTA"
            ]
        ],
        "2021-01-27": [
            [
                "IND",
                "CHA"
            ],
            [
                "DET",
                "CLE"
            ],
            [
                "SAC",
                "ORL"
            ],
            [
                "BKN",
                "ATL"
            ],
            [
                "DEN",
                "MIA"
            ],
            [
                "LAL",
                "PHI"
            ],
            [
                "MIL",
                "TOR"
            ],
            [
                "BOS",
                "SAS"
            ],
            [
                "WAS",
                "NOP"
            ],
            [
                "OKC",
                "PHX"
            ],
            [
                "DAL",
                "UTA"
            ],
            [
                "MIN",
                "GSW"
            ]
        ],
        "2021-01-28": [
            [
                "POR",
                "HOU"
            ],
            [
                "LAL",
                "DET"
            ],
            [
                "LAC",
                "MIA"
            ],
            [
                "GSW",
                "PHX"
            ]
        ],
        "2021-01-29": [
            [
                "IND",
                "CHA"
            ],
            [
                "ATL",
                "WAS"
            ],
            [
                "CLE",
                "NYK"
            ],
            [
                "SAC",
                "TOR"
            ],
            [
                "MIL",
                "NOP"
            ],
            [
                "LAC",
                "ORL"
            ],
            [
                "PHI",
                "MIN"
            ],
            [
                "BKN",
                "OKC"
            ],
            [
                "DEN",
                "SAS"
            ],
            [
                "DAL",
                "UTA"
            ]
        ],
        "2021-01-30": [
            [
                "POR",
                "CHI"
            ],
            [
                "MIL",
                "CHA"
            ],
            [
                "HOU",
                "NOP"
            ],
            [
                "SAC",
                "MIA"
            ],
            [
                "LAL",
                "BOS"
            ],
            [
                "MEM",
                "SAS"
            ],
            [
                "PHX",
                "DAL"
            ],
            [
                "DET",
                "GSW"
            ]
        ],
        "2021-01-31": [
            [
                "LAC",
                "NYK"
            ],
            [
                "UTA",
                "DEN"
            ],
            [
                "PHI",
                "IND"
            ],
            [
                "ORL",
                "TOR"
            ],
            [
                "BKN",
                "WAS"
            ],
            [
                "CLE",
                "MIN"
            ]
        ]
    },
    "March": {
        "2021-03-01": [
            [
                "DAL",
                "ORL"
            ],
            [
                "IND",
                "PHI"
            ],
            [
                "DEN",
                "CHI"
            ],
            [
                "UTA",
                "NOP"
            ],
            [
                "BKN",
                "SAS"
            ],
            [
                "CLE",
                "HOU"
            ],
            [
                "CHA",
                "POR"
            ]
        ],
        "2021-03-02": [
            [
                "MEM",
                "WAS"
            ],
            [
                "LAC",
                "BOS"
            ],
            [
                "ATL",
                "MIA"
            ],
            [
                "NYK",
                "SAS"
            ],
            [
                "DEN",
                "MIL"
            ],
            [
                "PHX",
                "LAL"
            ]
        ],
        "2021-03-03": [
            [
                "DET",
                "TOR"
            ],
            [
                "IND",
                "CLE"
            ],
            [
                "UTA",
                "PHI"
            ],
            [
                "BKN",
                "HOU"
            ],
            [
                "ATL",
                "ORL"
            ],
            [
                "CHA",
                "MIN"
            ],
            [
                "CHI",
                "NOP"
            ],
            [
                "OKC",
                "DAL"
            ],
            [
                "GSW",
                "POR"
            ],
            [
                "LAL",
                "SAC"
            ]
        ],
        "2021-03-04": [
            [
                "TOR",
                "BOS"
            ],
            [
                "LAC",
                "WAS"
            ],
            [
                "DET",
                "NYK"
            ],
            [
                "DEN",
                "IND"
            ],
            [
                "MIL",
                "MEM"
            ],
            [
                "MIA",
                "NOP"
            ],
            [
                "OKC",
                "SAS"
            ],
            [
                "GSW",
                "PHX"
            ],
            [
                "SAC",
                "POR"
            ]
        ],
        "2021-03-07": [
            [
                "LBN",
                "DRT"
            ]
        ],
        "2021-03-10": [
            [
                "WAS",
                "MEM"
            ],
            [
                "SAS",
                "DAL"
            ]
        ],
        "2021-03-11": [
            [
                "DET",
                "CHA"
            ],
            [
                "BOS",
                "BKN"
            ],
            [
                "ATL",
                "TOR"
            ],
            [
                "ORL",
                "MIA"
            ],
            [
                "PHI",
                "CHI"
            ],
            [
                "NYK",
                "MIL"
            ],
            [
                "MIN",
                "NOP"
            ],
            [
                "DAL",
                "OKC"
            ],
            [
                "GSW",
                "LAC"
            ],
            [
                "PHX",
                "POR"
            ],
            [
                "HOU",
                "SAC"
            ]
        ],
        "2021-03-12": [
            [
                "PHI",
                "WAS"
            ],
            [
                "DEN",
                "MEM"
            ],
            [
                "CLE",
                "NOP"
            ],
            [
                "MIA",
                "CHI"
            ],
            [
                "ORL",
                "SAS"
            ],
            [
                "HOU",
                "UTA"
            ],
            [
                "IND",
                "LAL"
            ]
        ],
        "2021-03-13": [
            [
                "NYK",
                "OKC"
            ],
            [
                "DET",
                "BKN"
            ],
            [
                "TOR",
                "CHA"
            ],
            [
                "MIL",
                "WAS"
            ],
            [
                "SAC",
                "ATL"
            ],
            [
                "POR",
                "MIN"
            ],
            [
                "IND",
                "PHX"
            ],
            [
                "DAL",
                "DEN"
            ]
        ],
        "2021-03-14": [
            [
                "MEM",
                "OKC"
            ],
            [
                "UTA",
                "GSW"
            ],
            [
                "SAS",
                "PHI"
            ],
            [
                "MIA",
                "ORL"
            ],
            [
                "CLE",
                "ATL"
            ],
            [
                "BOS",
                "HOU"
            ],
            [
                "POR",
                "MIN"
            ],
            [
                "TOR",
                "CHI"
            ],
            [
                "LAC",
                "NOP"
            ]
        ],
        "2021-03-15": [
            [
                "SAC",
                "CHA"
            ],
            [
                "MIL",
                "WAS"
            ],
            [
                "SAS",
                "DET"
            ],
            [
                "NYK",
                "BKN"
            ],
            [
                "LAC",
                "DAL"
            ],
            [
                "IND",
                "DEN"
            ],
            [
                "MEM",
                "PHX"
            ],
            [
                "LAL",
                "GSW"
            ]
        ],
        "2021-03-16": [
            [
                "UTA",
                "BOS"
            ],
            [
                "CLE",
                "MIA"
            ],
            [
                "NYK",
                "PHI"
            ],
            [
                "OKC",
                "CHI"
            ],
            [
                "ATL",
                "HOU"
            ],
            [
                "NOP",
                "POR"
            ],
            [
                "MIN",
                "LAL"
            ]
        ],
        "2021-03-17": [
            [
                "TOR",
                "DET"
            ],
            [
                "BKN",
                "IND"
            ],
            [
                "MIL",
                "PHI"
            ],
            [
                "SAC",
                "WAS"
            ],
            [
                "BOS",
                "CLE"
            ],
            [
                "SAS",
                "CHI"
            ],
            [
                "GSW",
                "HOU"
            ],
            [
                "MIA",
                "MEM"
            ],
            [
                "CHA",
                "DEN"
            ],
            [
                "LAC",
                "DAL"
            ]
        ],
        "2021-03-18": [
            [
                "UTA",
                "WAS"
            ],
            [
                "OKC",
                "ATL"
            ],
            [
                "ORL",
                "NYK"
            ],
            [
                "MIN",
                "PHX"
            ],
            [
                "NOP",
                "POR"
            ],
            [
                "CHA",
                "LAL"
            ]
        ],
        "2021-03-19": [
            [
                "SAS",
                "CLE"
            ],
            [
                "SAC",
                "BOS"
            ],
            [
                "IND",
                "MIA"
            ],
            [
                "BKN",
                "ORL"
            ],
            [
                "UTA",
                "TOR"
            ],
            [
                "DET",
                "HOU"
            ],
            [
                "GSW",
                "MEM"
            ],
            [
                "CHI",
                "DEN"
            ],
            [
                "MIN",
                "PHX"
            ],
            [
                "DAL",
                "POR"
            ]
        ],
        "2021-03-20": [
            [
                "ATL",
                "LAL"
            ],
            [
                "SAC",
                "PHI"
            ],
            [
                "GSW",
                "MEM"
            ],
            [
                "SAS",
                "MIL"
            ],
            [
                "CHA",
                "LAC"
            ]
        ],
        "2021-03-21": [
            [
                "IND",
                "MIA"
            ],
            [
                "OKC",
                "HOU"
            ],
            [
                "NOP",
                "DEN"
            ],
            [
                "ORL",
                "BOS"
            ],
            [
                "WAS",
                "BKN"
            ],
            [
                "TOR",
                "CLE"
            ],
            [
                "CHI",
                "DET"
            ],
            [
                "PHI",
                "NYK"
            ],
            [
                "LAL",
                "PHX"
            ],
            [
                "DAL",
                "POR"
            ]
        ],
        "2021-03-22": [
            [
                "SAC",
                "CLE"
            ],
            [
                "OKC",
                "MIN"
            ],
            [
                "CHA",
                "SAS"
            ],
            [
                "UTA",
                "CHI"
            ],
            [
                "TOR",
                "HOU"
            ],
            [
                "BOS",
                "MEM"
            ],
            [
                "IND",
                "MIL"
            ],
            [
                "ATL",
                "LAC"
            ]
        ],
        "2021-03-23": [
            [
                "DEN",
                "ORL"
            ],
            [
                "WAS",
                "NYK"
            ],
            [
                "LAL",
                "NOP"
            ],
            [
                "PHX",
                "MIA"
            ],
            [
                "PHI",
                "GSW"
            ],
            [
                "BKN",
                "POR"
            ]
        ],
        "2021-03-24": [
            [
                "DET",
                "IND"
            ],
            [
                "DEN",
                "TOR"
            ],
            [
                "BOS",
                "MIL"
            ],
            [
                "PHX",
                "ORL"
            ],
            [
                "CLE",
                "CHI"
            ],
            [
                "CHA",
                "HOU"
            ],
            [
                "DAL",
                "MIN"
            ],
            [
                "MEM",
                "OKC"
            ],
            [
                "LAC",
                "SAS"
            ],
            [
                "BKN",
                "UTA"
            ],
            [
                "ATL",
                "SAC"
            ]
        ],
        "2021-03-25": [
            [
                "POR",
                "MIA"
            ],
            [
                "WAS",
                "NYK"
            ],
            [
                "LAC",
                "SAS"
            ],
            [
                "PHI",
                "LAL"
            ],
            [
                "GSW",
                "SAC"
            ]
        ],
        "2021-03-26": [
            [
                "BKN",
                "DET"
            ],
            [
                "PHX",
                "TOR"
            ],
            [
                "BOS",
                "MIL"
            ],
            [
                "MIA",
                "CHA"
            ],
            [
                "POR",
                "ORL"
            ],
            [
                "HOU",
                "MIN"
            ],
            [
                "DEN",
                "NOP"
            ],
            [
                "IND",
                "DAL"
            ],
            [
                "MEM",
                "UTA"
            ],
            [
                "ATL",
                "GSW"
            ],
            [
                "CLE",
                "LAL"
            ]
        ],
        "2021-03-27": [
            [
                "DET",
                "WAS"
            ],
            [
                "NYK",
                "MIL"
            ],
            [
                "HOU",
                "MIN"
            ],
            [
                "CHI",
                "SAS"
            ],
            [
                "DAL",
                "NOP"
            ],
            [
                "BOS",
                "OKC"
            ],
            [
                "MEM",
                "UTA"
            ],
            [
                "PHI",
                "LAC"
            ],
            [
                "CLE",
                "SAC"
            ]
        ],
        "2021-03-28": [
            [
                "PHX",
                "CHA"
            ],
            [
                "POR",
                "TOR"
            ],
            [
                "ATL",
                "DEN"
            ],
            [
                "ORL",
                "LAL"
            ]
        ],
        "2021-03-29": [
            [
                "IND",
                "WAS"
            ],
            [
                "NOP",
                "BOS"
            ],
            [
                "MIN",
                "BKN"
            ],
            [
                "MIA",
                "NYK"
            ],
            [
                "TOR",
                "DET"
            ],
            [
                "MEM",
                "HOU"
            ],
            [
                "DAL",
                "OKC"
            ],
            [
                "SAC",
                "SAS"
            ],
            [
                "CLE",
                "UTA"
            ],
            [
                "CHI",
                "GSW"
            ],
            [
                "MIL",
                "LAC"
            ]
        ],
        "2021-03-30": [
            [
                "CHA",
                "WAS"
            ],
            [
                "PHI",
                "DEN"
            ],
            [
                "ATL",
                "PHX"
            ],
            [
                "ORL",
                "LAC"
            ]
        ],
        "2021-03-31": [
            [
                "POR",
                "DET"
            ],
            [
                "MIA",
                "IND"
            ],
            [
                "DAL",
                "BOS"
            ],
            [
                "HOU",
                "BKN"
            ],
            [
                "UTA",
                "MEM"
            ],
            [
                "NYK",
                "MIN"
            ],
            [
                "TOR",
                "OKC"
            ],
            [
                "SAC",
                "SAS"
            ],
            [
                "MIL",
                "LAL"
            ],
            [
                "CHI",
                "PHX"
            ]
        ]
    },
    "May": {
        "2021-05-01": [
            [
                "DET",
                "CHA"
            ],
            [
                "GSW",
                "HOU"
            ],
            [
                "CHI",
                "ATL"
            ],
            [
                "MIA",
                "CLE"
            ],
            [
                "MEM",
                "ORL"
            ],
            [
                "NOP",
                "MIN"
            ],
            [
                "IND",
                "OKC"
            ],
            [
                "WAS",
                "DAL"
            ],
            [
                "TOR",
                "UTA"
            ],
            [
                "DEN",
                "LAC"
            ]
        ],
        "2021-05-02": [
            [
                "BKN",
                "MIL"
            ],
            [
                "POR",
                "BOS"
            ],
            [
                "MIA",
                "CHA"
            ],
            [
                "SAC",
                "DAL"
            ],
            [
                "NYK",
                "HOU"
            ],
            [
                "PHX",
                "OKC"
            ],
            [
                "PHI",
                "SAS"
            ],
            [
                "TOR",
                "LAL"
            ]
        ],
        "2021-05-03": [
            [
                "ORL",
                "DET"
            ],
            [
                "IND",
                "WAS"
            ],
            [
                "GSW",
                "NOP"
            ],
            [
                "POR",
                "ATL"
            ],
            [
                "PHI",
                "CHI"
            ],
            [
                "NYK",
                "MEM"
            ],
            [
                "SAS",
                "UTA"
            ],
            [
                "DEN",
                "LAL"
            ]
        ],
        "2021-05-04": [
            [
                "PHX",
                "CLE"
            ],
            [
                "CHA",
                "DET"
            ],
            [
                "BKN",
                "MIL"
            ],
            [
                "DAL",
                "MIA"
            ],
            [
                "GSW",
                "NOP"
            ],
            [
                "SAC",
                "OKC"
            ],
            [
                "TOR",
                "LAC"
            ]
        ],
        "2021-05-05": [
            [
                "BOS",
                "ORL"
            ],
            [
                "POR",
                "CLE"
            ],
            [
                "MEM",
                "MIN"
            ],
            [
                "WAS",
                "MIL"
            ],
            [
                "PHX",
                "ATL"
            ],
            [
                "SAC",
                "IND"
            ],
            [
                "PHI",
                "HOU"
            ],
            [
                "NYK",
                "DEN"
            ],
            [
                "SAS",
                "UTA"
            ]
        ],
        "2021-05-06": [
            [
                "CHI",
                "CHA"
            ],
            [
                "WAS",
                "TOR"
            ],
            [
                "BKN",
                "DAL"
            ],
            [
                "MEM",
                "DET"
            ],
            [
                "ATL",
                "IND"
            ],
            [
                "OKC",
                "GSW"
            ],
            [
                "LAL",
                "LAC"
            ]
        ],
        "2021-05-07": [
            [
                "NOP",
                "PHI"
            ],
            [
                "BOS",
                "CHI"
            ],
            [
                "ORL",
                "CHA"
            ],
            [
                "MIN",
                "MIA"
            ],
            [
                "HOU",
                "MIL"
            ],
            [
                "CLE",
                "DAL"
            ],
            [
                "DEN",
                "UTA"
            ],
            [
                "NYK",
                "PHX"
            ],
            [
                "LAL",
                "POR"
            ],
            [
                "SAS",
                "SAC"
            ]
        ],
        "2021-05-08": [
            [
                "WAS",
                "IND"
            ],
            [
                "DET",
                "PHI"
            ],
            [
                "MEM",
                "TOR"
            ],
            [
                "BKN",
                "DEN"
            ],
            [
                "HOU",
                "UTA"
            ],
            [
                "OKC",
                "GSW"
            ],
            [
                "SAS",
                "POR"
            ]
        ],
        "2021-05-09": [
            [
                "MIA",
                "BOS"
            ],
            [
                "NYK",
                "LAC"
            ],
            [
                "NOP",
                "CHA"
            ],
            [
                "DAL",
                "CLE"
            ],
            [
                "MIN",
                "ORL"
            ],
            [
                "CHI",
                "DET"
            ],
            [
                "PHX",
                "LAL"
            ],
            [
                "OKC",
                "SAC"
            ]
        ],
        "2021-05-10": [
            [
                "WAS",
                "ATL"
            ],
            [
                "IND",
                "CLE"
            ],
            [
                "NOP",
                "MEM"
            ],
            [
                "MIL",
                "SAS"
            ],
            [
                "UTA",
                "GSW"
            ],
            [
                "HOU",
                "POR"
            ]
        ],
        "2021-05-11": [
            [
                "DEN",
                "CHA"
            ],
            [
                "MIA",
                "BOS"
            ],
            [
                "MIN",
                "DET"
            ],
            [
                "LAC",
                "TOR"
            ],
            [
                "PHI",
                "IND"
            ],
            [
                "BKN",
                "CHI"
            ],
            [
                "DAL",
                "MEM"
            ],
            [
                "ORL",
                "MIL"
            ],
            [
                "PHX",
                "GSW"
            ],
            [
                "OKC",
                "SAC"
            ],
            [
                "NYK",
                "LAL"
            ]
        ],
        "2021-05-12": [
            [
                "WAS",
                "ATL"
            ],
            [
                "SAS",
                "BKN"
            ],
            [
                "BOS",
                "CLE"
            ],
            [
                "NOP",
                "DAL"
            ],
            [
                "POR",
                "UTA"
            ],
            [
                "HOU",
                "LAL"
            ]
        ],
        "2021-05-13": [
            [
                "LAC",
                "CHA"
            ],
            [
                "MIL",
                "IND"
            ],
            [
                "SAS",
                "NYK"
            ],
            [
                "ORL",
                "ATL"
            ],
            [
                "PHI",
                "MIA"
            ],
            [
                "SAC",
                "MEM"
            ],
            [
                "TOR",
                "CHI"
            ],
            [
                "DEN",
                "MIN"
            ],
            [
                "POR",
                "PHX"
            ]
        ],
        "2021-05-14": [
            [
                "CLE",
                "WAS"
            ],
            [
                "DEN",
                "DET"
            ],
            [
                "ORL",
                "PHI"
            ],
            [
                "UTA",
                "OKC"
            ],
            [
                "SAC",
                "MEM"
            ],
            [
                "TOR",
                "DAL"
            ],
            [
                "LAC",
                "HOU"
            ],
            [
                "NOP",
                "GSW"
            ]
        ],
        "2021-05-15": [
            [
                "CHI",
                "BKN"
            ],
            [
                "LAL",
                "IND"
            ],
            [
                "MIA",
                "MIL"
            ],
            [
                "BOS",
                "MIN"
            ],
            [
                "CHA",
                "NYK"
            ],
            [
                "PHX",
                "SAS"
            ]
        ],
        "2021-05-16": [
            [
                "HOU",
                "ATL"
            ],
            [
                "CLE",
                "BKN"
            ],
            [
                "MIL",
                "CHI"
            ],
            [
                "MIA",
                "DET"
            ],
            [
                "MEM",
                "GSW"
            ],
            [
                "DAL",
                "MIN"
            ],
            [
                "LAL",
                "NOP"
            ],
            [
                "BOS",
                "NYK"
            ],
            [
                "LAC",
                "OKC"
            ],
            [
                "ORL",
                "PHI"
            ],
            [
                "DEN",
                "POR"
            ],
            [
                "UTA",
                "SAC"
            ],
            [
                "PHX",
                "SAS"
            ],
            [
                "IND",
                "TOR"
            ],
            [
                "CHA",
                "WAS"
            ]
        ]
    }
}