Q = {
    "410.l.136341.t.1": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "James Harden",
            "player_id": 4563,
            "position_type": "P",
            "status": "",
            "team": "BKN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "LeBron James",
            "player_id": 3704,
            "position_type": "P",
            "status": "",
            "team": "LAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Cade Cunningham",
            "player_id": 6512,
            "position_type": "P",
            "status": "O",
            "team": "DET"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jimmy Butler",
            "player_id": 4912,
            "position_type": "P",
            "status": "GTD",
            "team": "MIA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "OG Anunoby",
            "player_id": 5836,
            "position_type": "P",
            "status": "O",
            "team": "TOR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "John Collins",
            "player_id": 5832,
            "position_type": "P",
            "status": "",
            "team": "ATL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Evan Mobley",
            "player_id": 6514,
            "position_type": "P",
            "status": "",
            "team": "CLE"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kelly Olynyk",
            "player_id": 5164,
            "position_type": "P",
            "status": "",
            "team": "DET"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Nerlens Noel",
            "player_id": 5157,
            "position_type": "P",
            "status": "GTD",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kyle Anderson",
            "player_id": 5341,
            "position_type": "P",
            "status": "O",
            "team": "MEM"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Matisse Thybulle",
            "player_id": 6208,
            "position_type": "P",
            "status": "INJ",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Dillon Brooks",
            "player_id": 5858,
            "position_type": "P",
            "status": "INJ",
            "team": "MEM"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Alperen Sengun",
            "player_id": 6558,
            "position_type": "P",
            "status": "",
            "team": "HOU"
        }
    ],
    "410.l.136341.t.10": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Luka Doncic",
            "player_id": 6014,
            "position_type": "P",
            "status": "",
            "team": "DAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Devin Booker",
            "player_id": 5473,
            "position_type": "P",
            "status": "",
            "team": "PHX"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Collin Sexton",
            "player_id": 6019,
            "position_type": "P",
            "status": "O",
            "team": "CLE"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Scottie Barnes",
            "player_id": 6515,
            "position_type": "P",
            "status": "",
            "team": "TOR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Myles Turner",
            "player_id": 5471,
            "position_type": "P",
            "status": "",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Isaiah Stewart",
            "player_id": 6408,
            "position_type": "P",
            "status": "",
            "team": "DET"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Rudy Gobert",
            "player_id": 5197,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Mason Plumlee",
            "player_id": 5192,
            "position_type": "P",
            "status": "",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Malcolm Brogdon",
            "player_id": 5667,
            "position_type": "P",
            "status": "O",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Devonte' Graham",
            "player_id": 6045,
            "position_type": "P",
            "status": "",
            "team": "NOP"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jae'Sean Tate",
            "player_id": 6463,
            "position_type": "P",
            "status": "",
            "team": "HOU"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Seth Curry",
            "player_id": 5245,
            "position_type": "P",
            "status": "O",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Joe Ingles",
            "player_id": 5393,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        }
    ],
    "410.l.136341.t.11": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Damian Lillard",
            "player_id": 5012,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Marcus Smart",
            "player_id": 5317,
            "position_type": "P",
            "status": "O",
            "team": "BOS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Russell Westbrook",
            "player_id": 4390,
            "position_type": "P",
            "status": "",
            "team": "LAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Tobias Harris",
            "player_id": 4901,
            "position_type": "P",
            "status": "O",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jaren Jackson Jr.",
            "player_id": 6015,
            "position_type": "P",
            "status": "O",
            "team": "MEM"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Klay Thompson",
            "player_id": 4892,
            "position_type": "P",
            "status": "INJ",
            "team": "GSW"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Nikola Vucevic",
            "player_id": 4897,
            "position_type": "P",
            "status": "",
            "team": "CHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jonas Valanciunas",
            "player_id": 4886,
            "position_type": "P",
            "status": "",
            "team": "NOP"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Ben Simmons",
            "player_id": 5600,
            "position_type": "P",
            "status": "O",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Andre Drummond",
            "player_id": 5015,
            "position_type": "P",
            "status": "",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Duncan Robinson",
            "player_id": 6073,
            "position_type": "P",
            "status": "",
            "team": "MIA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jamal Murray",
            "player_id": 5638,
            "position_type": "P",
            "status": "INJ",
            "team": "DEN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Dennis Schroder",
            "player_id": 5187,
            "position_type": "P",
            "status": "O",
            "team": "BOS"
        }
    ],
    "410.l.136341.t.12": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Fred VanVleet",
            "player_id": 5727,
            "position_type": "P",
            "status": "INJ",
            "team": "TOR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jaylen Brown",
            "player_id": 5602,
            "position_type": "P",
            "status": "INJ",
            "team": "BOS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "D'Angelo Russell",
            "player_id": 5433,
            "position_type": "P",
            "status": "",
            "team": "MIN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Caris LeVert",
            "player_id": 5651,
            "position_type": "P",
            "status": "O",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Giannis Antetokounmpo",
            "player_id": 5185,
            "position_type": "P",
            "status": "",
            "team": "MIL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kristaps Porzingis",
            "player_id": 5464,
            "position_type": "P",
            "status": "",
            "team": "DAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Clint Capela",
            "player_id": 5336,
            "position_type": "P",
            "status": "GTD",
            "team": "ATL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jakob Poeltl",
            "player_id": 5640,
            "position_type": "P",
            "status": "",
            "team": "SAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Nickeil Alexander0Walker",
            "player_id": 6205,
            "position_type": "P",
            "status": "",
            "team": "NOP"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Mo Bamba",
            "player_id": 6017,
            "position_type": "P",
            "status": "",
            "team": "ORL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Josh Giddey",
            "player_id": 6548,
            "position_type": "P",
            "status": "",
            "team": "OKC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Tyrese Maxey",
            "player_id": 6413,
            "position_type": "P",
            "status": "O",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kawhi Leonard",
            "player_id": 4896,
            "position_type": "P",
            "status": "INJ",
            "team": "LAC"
        }
    ],
    "410.l.136341.t.2": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jrue Holiday",
            "player_id": 4622,
            "position_type": "P",
            "status": "",
            "team": "MIL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Norman Powell",
            "player_id": 5506,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jordan Poole",
            "player_id": 6216,
            "position_type": "P",
            "status": "",
            "team": "GSW"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Paul George",
            "player_id": 4725,
            "position_type": "P",
            "status": "O",
            "team": "LAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jayson Tatum",
            "player_id": 5765,
            "position_type": "P",
            "status": "O",
            "team": "BOS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Christian Wood",
            "player_id": 5583,
            "position_type": "P",
            "status": "",
            "team": "HOU"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jarrett Allen",
            "player_id": 5835,
            "position_type": "P",
            "status": "",
            "team": "CLE"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jusuf Nurkic",
            "player_id": 5327,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Harrison Barnes",
            "player_id": 5013,
            "position_type": "P",
            "status": "",
            "team": "SAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Spencer Dinwiddie",
            "player_id": 5349,
            "position_type": "P",
            "status": "",
            "team": "WAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Aaron Gordon",
            "player_id": 5295,
            "position_type": "P",
            "status": "",
            "team": "DEN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Tim Hardaway Jr.",
            "player_id": 5194,
            "position_type": "P",
            "status": "",
            "team": "DAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Terance Mann",
            "player_id": 6236,
            "position_type": "P",
            "status": "",
            "team": "LAC"
        }
    ],
    "410.l.136341.t.3": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Ja Morant",
            "player_id": 6164,
            "position_type": "P",
            "status": "O",
            "team": "MEM"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Anthony Edwards",
            "player_id": 6355,
            "position_type": "P",
            "status": "",
            "team": "MIN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Terry Rozier",
            "player_id": 5476,
            "position_type": "P",
            "status": "O",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Gary Trent Jr.",
            "player_id": 6048,
            "position_type": "P",
            "status": "",
            "team": "TOR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Domantas Sabonis",
            "player_id": 5642,
            "position_type": "P",
            "status": "",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "RJ Barrett",
            "player_id": 6165,
            "position_type": "P",
            "status": "",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Karl0Anthony Towns",
            "player_id": 5432,
            "position_type": "P",
            "status": "",
            "team": "MIN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Mitchell Robinson",
            "player_id": 6047,
            "position_type": "P",
            "status": "INJ",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jordan Clarkson",
            "player_id": 5357,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Luguentz Dort",
            "player_id": 6254,
            "position_type": "P",
            "status": "",
            "team": "OKC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Steven Adams",
            "player_id": 5163,
            "position_type": "P",
            "status": "O",
            "team": "MEM"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Davis Bertans",
            "player_id": 4926,
            "position_type": "P",
            "status": "",
            "team": "WAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Alex Caruso",
            "player_id": 5754,
            "position_type": "P",
            "status": "",
            "team": "CHI"
        }
    ],
    "410.l.136341.t.4": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "De'Aaron Fox",
            "player_id": 5767,
            "position_type": "P",
            "status": "",
            "team": "SAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Gordon Hayward",
            "player_id": 4724,
            "position_type": "P",
            "status": "O",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Darius Garland",
            "player_id": 6167,
            "position_type": "P",
            "status": "O",
            "team": "CLE"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Khris Middleton",
            "player_id": 5073,
            "position_type": "P",
            "status": "",
            "team": "MIL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Anthony Davis",
            "player_id": 5007,
            "position_type": "P",
            "status": "",
            "team": "LAL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Darius Bazley",
            "player_id": 6211,
            "position_type": "P",
            "status": "",
            "team": "OKC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Bam Adebayo",
            "player_id": 5827,
            "position_type": "P",
            "status": "",
            "team": "MIA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "PJ Washington",
            "player_id": 6174,
            "position_type": "P",
            "status": "",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "De'Andre Hunter",
            "player_id": 6166,
            "position_type": "P",
            "status": "",
            "team": "ATL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Joe Harris",
            "player_id": 5344,
            "position_type": "P",
            "status": "",
            "team": "BKN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Patrick Williams",
            "player_id": 6396,
            "position_type": "P",
            "status": "GTD",
            "team": "CHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Precious Achiuwa",
            "player_id": 6412,
            "position_type": "P",
            "status": "",
            "team": "TOR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Pascal Siakam",
            "player_id": 5658,
            "position_type": "P",
            "status": "INJ",
            "team": "TOR"
        }
    ],
    "410.l.136341.t.5": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Trae Young",
            "player_id": 6016,
            "position_type": "P",
            "status": "",
            "team": "ATL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Bradley Beal",
            "player_id": 5009,
            "position_type": "P",
            "status": "",
            "team": "WAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Mike Conley",
            "player_id": 4246,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Michael Porter Jr.",
            "player_id": 6025,
            "position_type": "P",
            "status": "",
            "team": "DEN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Brandon Ingram",
            "player_id": 5601,
            "position_type": "P",
            "status": "O",
            "team": "NOP"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Draymond Green",
            "player_id": 5069,
            "position_type": "P",
            "status": "O",
            "team": "GSW"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Robert Covington",
            "player_id": 5253,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Keldon Johnson",
            "player_id": 6217,
            "position_type": "P",
            "status": "",
            "team": "SAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Bojan Bogdanovic",
            "player_id": 4913,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Justin Holiday",
            "player_id": 5142,
            "position_type": "P",
            "status": "O",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Nicolas Batum",
            "player_id": 4487,
            "position_type": "P",
            "status": "",
            "team": "LAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Monte Morris",
            "player_id": 5864,
            "position_type": "P",
            "status": "",
            "team": "DEN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Chris Boucher",
            "player_id": 5894,
            "position_type": "P",
            "status": "INJ",
            "team": "TOR"
        }
    ],
    "410.l.136341.t.6": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Stephen Curry",
            "player_id": 4612,
            "position_type": "P",
            "status": "O",
            "team": "GSW"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Shai Gilgeous0Alexander",
            "player_id": 6022,
            "position_type": "P",
            "status": "",
            "team": "OKC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Tyrese Haliburton",
            "player_id": 6404,
            "position_type": "P",
            "status": "",
            "team": "SAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Saddiq Bey",
            "player_id": 6411,
            "position_type": "P",
            "status": "GTD",
            "team": "DET"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Zion Williamson",
            "player_id": 6163,
            "position_type": "P",
            "status": "INJ",
            "team": "NOP"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Richaun Holmes",
            "player_id": 5497,
            "position_type": "P",
            "status": "",
            "team": "SAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Robert Williams",
            "player_id": 6038,
            "position_type": "P",
            "status": "",
            "team": "BOS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Al Horford",
            "player_id": 4245,
            "position_type": "P",
            "status": "O",
            "team": "BOS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kyrie Irving",
            "player_id": 4840,
            "position_type": "P",
            "status": "O",
            "team": "BKN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jalen Green",
            "player_id": 6513,
            "position_type": "P",
            "status": "",
            "team": "HOU"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "T.J. McConnell",
            "player_id": 5582,
            "position_type": "P",
            "status": "",
            "team": "IND"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jonathan Isaac",
            "player_id": 5768,
            "position_type": "P",
            "status": "INJ",
            "team": "ORL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "De'Anthony Melton",
            "player_id": 6057,
            "position_type": "P",
            "status": "O",
            "team": "MEM"
        }
    ],
    "410.l.136341.t.7": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "LaMelo Ball",
            "player_id": 6395,
            "position_type": "P",
            "status": "",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "CJ McCollum",
            "player_id": 5161,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Dejounte Murray",
            "player_id": 5660,
            "position_type": "P",
            "status": "",
            "team": "SAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Andrew Wiggins",
            "player_id": 5292,
            "position_type": "P",
            "status": "",
            "team": "GSW"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Nikola Jokic",
            "player_id": 5352,
            "position_type": "P",
            "status": "",
            "team": "DEN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Bogdan Bogdanovic",
            "player_id": 5338,
            "position_type": "P",
            "status": "",
            "team": "ATL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Deandre Ayton",
            "player_id": 5958,
            "position_type": "P",
            "status": "",
            "team": "PHX"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Wendell Carter Jr.",
            "player_id": 6018,
            "position_type": "P",
            "status": "",
            "team": "ORL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jalen Suggs",
            "player_id": 6516,
            "position_type": "P",
            "status": "",
            "team": "ORL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Larry Nance Jr.",
            "player_id": 5487,
            "position_type": "P",
            "status": "",
            "team": "POR"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kelly Oubre Jr.",
            "player_id": 5475,
            "position_type": "P",
            "status": "GTD",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Derrick Rose",
            "player_id": 4387,
            "position_type": "P",
            "status": "",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Enes Kanter",
            "player_id": 4899,
            "position_type": "P",
            "status": "",
            "team": "BOS"
        }
    ],
    "410.l.136341.t.8": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Lonzo Ball",
            "player_id": 5764,
            "position_type": "P",
            "status": "",
            "team": "CHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Zach LaVine",
            "player_id": 5324,
            "position_type": "P",
            "status": "",
            "team": "CHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Derrick White",
            "player_id": 5842,
            "position_type": "P",
            "status": "",
            "team": "SAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Buddy Hield",
            "player_id": 5637,
            "position_type": "P",
            "status": "",
            "team": "SAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Joel Embiid",
            "player_id": 5294,
            "position_type": "P",
            "status": "",
            "team": "PHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Julius Randle",
            "player_id": 5318,
            "position_type": "P",
            "status": "",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Brook Lopez",
            "player_id": 4472,
            "position_type": "P",
            "status": "",
            "team": "MIL"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Lauri Markkanen",
            "player_id": 5769,
            "position_type": "P",
            "status": "",
            "team": "CLE"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kyle Lowry",
            "player_id": 4152,
            "position_type": "P",
            "status": "",
            "team": "MIA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Tyler Herro",
            "player_id": 6175,
            "position_type": "P",
            "status": "",
            "team": "MIA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kyle Kuzma",
            "player_id": 5840,
            "position_type": "P",
            "status": "",
            "team": "WAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jaden McDaniels",
            "player_id": 6420,
            "position_type": "P",
            "status": "",
            "team": "MIN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Aleksej Pokusevski",
            "player_id": 6409,
            "position_type": "P",
            "status": "",
            "team": "OKC"
        }
    ],
    "410.l.136341.t.9": [
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Donovan Mitchell",
            "player_id": 5826,
            "position_type": "P",
            "status": "",
            "team": "UTA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Mikal Bridges",
            "player_id": 6021,
            "position_type": "P",
            "status": "",
            "team": "PHX"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Chris Paul",
            "player_id": 3930,
            "position_type": "P",
            "status": "",
            "team": "PHX"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kevin Durant",
            "player_id": 4244,
            "position_type": "P",
            "status": "",
            "team": "BKN"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "DeMar DeRozan",
            "player_id": 4614,
            "position_type": "P",
            "status": "",
            "team": "CHI"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Jerami Grant",
            "player_id": 5350,
            "position_type": "P",
            "status": "",
            "team": "DET"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Daniel Gafford",
            "player_id": 6226,
            "position_type": "P",
            "status": "",
            "team": "WAS"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Ivica Zubac",
            "player_id": 5663,
            "position_type": "P",
            "status": "",
            "team": "LAC"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kevin Porter Jr.",
            "player_id": 6218,
            "position_type": "P",
            "status": "",
            "team": "HOU"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Kemba Walker",
            "player_id": 4890,
            "position_type": "P",
            "status": "",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Miles Bridges",
            "player_id": 6023,
            "position_type": "P",
            "status": "",
            "team": "CHA"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Evan Fournier",
            "player_id": 5054,
            "position_type": "P",
            "status": "",
            "team": "NYK"
        },
        {
            "3PTM": 0.0,
            "AST": 0.0,
            "BLK": 0.0,
            "FG%": 0.0,
            "FT%": 0.0,
            "PTS": 0.0,
            "REB": 0.0,
            "ST": 0.0,
            "TO": 0.0,
            "name": "Thaddeus Young",
            "player_id": 4290,
            "position_type": "P",
            "status": "",
            "team": "SAS"
        }
    ]
}